name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository_owner == 'homebysix'
    runs-on: ubuntu-latest

    steps:
      - name: Clone this repository
        uses: actions/checkout@v2
        with:
          path: main

      - name: Update Processor Docs
        working-directory: main
        # env:
        #   PA_TOKEN: ${{ secrets.PAT_SECRET }}
        run: python3 ./Scripts/generate_processor_docs.py

      # - name: Commit index
      #   working-directory: main
      #   env:
      #     PA_TOKEN: ${{ secrets.PAT_SECRET }}
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add index.json || true
      #     git commit -m "Rebuild index" index.json || true
      #     git push --set-upstream origin main || true
