name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository_owner == 'homebysix'
    runs-on: ubuntu-latest

    steps:
      - name: Clone this repository
        uses: actions/checkout@v2
        with:
          path: main

      - name: Install Python Requirements
        working-directory: main
        run: python3 -m pip install -r requirements.txt
        continue-on-error: true

      - name: Configure Git
        working-directory: main
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Update Processor Docs
        working-directory: main/Scripts
        # env:
        #   PA_TOKEN: ${{ secrets.PAT_SECRET }}
        run: python3 generate_processor_docs.py "0.0.0"
